# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ChatExample' do

  use_frameworks!

  # Pods for ChatExample
  pod 'MessageKit', :path => '../'

end
